ALTER TABLE "User"
  ADD COLUMN "avatarUrl" TEXT,
  ADD COLUMN "bio" TEXT,
  ADD COLUMN "timezone" TEXT NOT NULL DEFAULT 'UTC',
  ADD COLUMN "marketingEmails" BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN "productUpdates" BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN "weeklyDigestEmails" BOOLEAN NOT NULL DEFAULT TRUE;
