ALTER TABLE IF EXISTS "ReadingListEntry"
  ALTER COLUMN "altTitles" DROP DEFAULT,
  ALTER COLUMN "languages" DROP DEFAULT,
  ALTER COLUMN "tags" DROP DEFAULT,
  ALTER COLUMN "updatedAt" DROP DEFAULT;
